routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin');
});

Auth::routes(['register' => true]);

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['namespace' => 'App\Http\Controllers\Admin', 'prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('users', 'UsersController');
    Route::resource('contrats', 'ContratsController');
    Route::resource('personnes', 'PersonnesController');
    Route::resource('pages', 'PagesController');
    Route::resource('activitylogs', 'ActivityLogsController')->only([
        'index', 'show', 'destroy'
    ]);
    Route::resource('admin/settings', 'SettingsController');
    Route::get('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
    Route::post('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
});

Route::group(['namespace' => 'App\Http\Controllers\Admin', 'prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'AdminController@index');
    Route::get('evaluations/create/{id}', 'EvaluationController@create');
    Route::resource('annee', 'AnneeController');
    Route::resource('cycles', 'CyclesController');
    Route::resource('niveau', 'NiveauController');
    Route::resource('classes', 'ClassesController');
    Route::resource('eleves', 'ElevesController');
    
    Route::resource('matieres', 'MatieresController');
    Route::resource('evaluations', 'EvaluationController');
    Route::resource('notes', 'NoteController');

    //ListeElevesParClasseController

    Route::resource('matieres', 'MatieresController');
});

//Editions
Route::group(['namespace' => 'App\Http\Controllers\Editions', 'prefix' => 'editions', 'middleware' => ['auth']], function () {

    //Liste des Eleves Par Classe
    Route::get('classe/eleves/{classe_id}', 'ListeElevesParClasseController@tousLesEleves')->name('listes.classe.eleves');
    // Exporter les eleves en fichier Excel
    Route::post("eleves/export", "EelveExcelController@export")->name('eleves.excel.export');
});

// Bulletins
Route::get('bulletins/eleves/{eleve}/{eval}', '\App\Http\Controllers\Admin\EleveController@bulletin')->name('bulletins.eleve.eval');
Route::get('bulletins/classe/{classe}/{eval}', '\App\Http\Controllers\Admin\ClassesController@bulletin')->name('bulletins.classe.eval');
Route::resource('bulletins', 'BulletinController');

app/Models/Evaluation.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Evaluation extends Model
{
    use SoftDeletes;

    public $table = 'evaluations';

    protected $dates = [
        'updated_at',
        'created_at',
        'deleted_at',
        'date_evaluation',
    ];

    protected $fillable = [
        'type',
        'matiere_id',
        'classe_id',
        'created_at',
        'updated_at',
        'deleted_at',
        'date_evaluation',
    ];

    const TYPE_SELECT = [
        'D'  => 'إختبار',
        'C1' => 'إمتحان الفصل الأول',
        'C2' => 'إمتحان الفصل الثاني',
        'C3' => 'إمتحان التجاوز',
    ];

    public function evaluationNotes()
    {
        return $this->hasMany(Note::class, 'evaluation_id', 'id');
    }

    public function getDateEvaluationAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setDateEvaluationAttribute($value)
    {
        $this->attributes['date_evaluation'] = $value ? Carbon::createFromFormat('Y-m-d', $value)->format('Y-m-d') : null;
    }

    public function matiere()
    {
        return $this->belongsTo(Matiere::class, 'matiere_id');
    }
    public function classe()
    {
        return $this->belongsTo(Classe::class, 'classe_id');
    }
}

app/Http/Controllers/Admin/EvaluationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Evaluation;
use App\Http\Controllers\Controller;

use App\Models\Matiere;
use App\Models\Classe;
use App\Models\Note;
use App\Models\Eleve;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class EvaluationController extends Controller
{
    public function index(Request $request)
    {
        //abort_if(Gate::denies('evaluation_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $evaluations = Evaluation::all();
        $classes = Classe::all();
        $classe_id = "";
        $type = "";

        if($request->classe_id){
            $evaluations = $evaluations->where('classe_id' , $request->classe_id);
            $classe_id = $request->classe_id;
        }

        if($request->type){
            $evaluations = $evaluations->where('type' , $request->type);
            $type = $request->type;
        }

        return view('admin.evaluations.index', compact('evaluations', 'classes', 'classe_id', 'type'));
    }

    public function create($id = null)
    {
        //abort_if(Gate::denies('evaluation_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        if($id==null){
            $classes = Classe::all();//->pluck('nom', 'id')->prepend(trans('Slectionner ...'), '');
            //dd($classes);
            return view('admin.evaluations.classes', compact('classes'));
        }
        else{
            $classe = Classe::find($id);
            $matieres = Matiere::where('niveau_id',$classe->niveau_id)->get()->pluck('libelle', 'id')->prepend(trans('Slectionner ...'), '');
            //dd($matieres);
            return view('admin.evaluations.create', compact('matieres','classe'));
        }
    }

    public function store(Request $request)
    {
        $evaluation = Evaluation::create($request->all());
        //dd($evaluation);
        $eleves = Eleve::where('classe_id',$evaluation->classe_id)->get();

        foreach ($eleves as $key => $eleve) {
            $note = Note::create([ 'eleve_id' => $eleve->id  , 'evaluation_id' => $evaluation->id , 'valeur' => 0 ]);
        }

        return redirect()->route('evaluations.index');
    }

    public function edit(Evaluation $evaluation)
    {
        //abort_if(Gate::denies('evaluation_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        //$matieres = Matiere::all()->pluck('libelle', 'id')->prepend(trans('Slectionner ...'), '');
        $classe = Classe::find($evaluation->classe_id);
        $matieres = Matiere::where('niveau_id',$classe->niveau_id)->get()->pluck('libelle', 'id')->prepend(trans('Slectionner ...'), '');

        $evaluation->load('matiere');

        return view('admin.evaluations.edit', compact('matieres', 'evaluation'));
    }

    public function update(Request $request, Evaluation $evaluation)
    {
        $evaluation->update($request->all());
        foreach ($request->notes as $key => $value) {

            $note = Note::find($key);
            $note->valeur = $value;
            $note->save();
        }

        return redirect()->route('evaluations.index');
    }

    public function show(Evaluation $evaluation)
    {
        //abort_if(Gate::denies('evaluation_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $evaluation->load('matiere');

        return view('admin.evaluations.show', compact('evaluation'));
    }

    public function destroy(Evaluation $evaluation)
    {
        //abort_if(Gate::denies('evaluation_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        foreach ($evaluation->evaluationNotes as $key => $note) {
            $note->delete();
        }
        $evaluation->delete();

        return back();
    }

    public function massDestroy(Request $request)
    {
        Evaluation::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/evaluations/classes.blade.php
@extends('layouts.backend')
@section('content')
<div class="card">
    <div class="card-header">
        {{ trans('Classe') }} {{ trans('Liste') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Classe">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                           #
                        </th>
                        <th>
                            Classe
                        <th>
                            Année
                        </th>
                        <th>
                            Etat
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($classes as $key => $classes)
                        <tr data-entry-id="{{ $classes->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $classes->id ?? '' }}
                            </td>
                            <td>
                                {{ $classes->niveau->libelle ?? '' }}
                            </td>
                            <td>
                                {{ $classes->annee->libelle ?? '' }}
                            </td>
                            <td>
                                {{ App\Models\Classe::ETAT_RADIO[$classes->etat] ?? '' }}
                            </td>
                            <td>
                                <a class="btn btn-success" href="{{ url('/admin/evaluations/create/'.$classes->id) }}">
                                    {{ trans('Ajouter') }} {{ trans('Evaluation') }}
                                </a>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('classes_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.classes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Classe:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/evaluations/create.blade.php
@extends('layouts.backend')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Ajouter') }} {{ trans('Evaluation') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <table class=" table table-bordered table-striped table-hover">
                <tr data-entry-id="{{ $classe->id }}">
                    <td>
                        Classe :
                    </td>
                    <td>
                        {{ $classe->nom ?? '' }}
                    </td>
                    <td>
                        {{ $classe->annee->libelle ?? '' }}
                    </td>
                    <td>
                        {{ App\Models\Classe::ETAT_RADIO[$classe->etat] ?? '' }}
                    </td>

                </tr>
            </table>
        </div>
        <hr/>
        <form method="POST" action="{{ route("evaluations.store") }}" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="classe_id" value="{{$classe->id}}" />
            <div class="form-group">
                <label for="date_evaluation">{{ trans('date_evaluation') }}</label>

                <input class="form-control date {{ $errors->has('date_evaluation') ? 'is-invalid' : '' }}" type="text" name="date_evaluation" id="date_evaluation" value="{{ old('date_evaluation') }}">
                @if($errors->has('date_evaluation'))
                    <div class="invalid-feedback">
                        {{ $errors->first('date_evaluation') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('date_evaluation_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="matiere_id">{{ trans('matiere') }}</label>
                <select class="form-control select2 {{ $errors->has('matiere') ? 'is-invalid' : '' }}" name="matiere_id" id="matiere_id" required>
                    @foreach($matieres as $id => $matiere)
                        <option value="{{ $id }}" {{ old('matiere_id') == $id ? 'selected' : '' }}>{{ $matiere }}</option>
                    @endforeach
                </select>
                @if($errors->has('matiere_id'))
                    <div class="invalid-feedback">
                        {{ $errors->first('matiere_id') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('matiere_helper') }}</span>
            </div>
            <div class="form-group">
                <label>{{ trans('type') }}</label>
                <select class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}" name="type" id="type">
                    <option value disabled {{ old('type', null) === null ? 'selected' : '' }}>{{ trans('Slectionner ...') }}</option>
                    @foreach(App\Models\Evaluation::TYPE_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('type', '') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('type'))
                    <div class="invalid-feedback">
                        {{ $errors->first('type') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('type_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('Enregistrer') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/evaluations/edit.blade.php
@extends('layouts.backend')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Modifier') }} {{ trans('Evaluation') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("evaluations.update", [$evaluation->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="date_evaluation">{{ trans('date_evaluation') }}</label>
                <input class="form-control date {{ $errors->has('date_evaluation') ? 'is-invalid' : '' }}" type="text" name="date_evaluation" id="date_evaluation" value="{{ old('date_evaluation', $evaluation->date_evaluation) }}">
                @if($errors->has('date_evaluation'))
                    <div class="invalid-feedback">
                        {{ $errors->first('date_evaluation') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('date_evaluation_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="matiere_id">{{ trans('matiere') }}</label>
                <select class="form-control select2 {{ $errors->has('matiere') ? 'is-invalid' : '' }}" name="matiere_id" id="matiere_id" required>
                    @foreach($matieres as $id => $matiere)
                        <option value="{{ $id }}" {{ ($evaluation->matiere ? $evaluation->matiere->id : old('matiere_id')) == $id ? 'selected' : '' }}>{{ $matiere }}</option>
                    @endforeach
                </select>
                @if($errors->has('matiere_id'))
                    <div class="invalid-feedback">
                        {{ $errors->first('matiere_id') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('matiere_helper') }}</span>
            </div>
            <div class="form-group">
                <label>{{ trans('type') }}</label>
                <select class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}" name="type" id="type">
                    <option value disabled {{ old('type', null) === null ? 'selected' : '' }}>{{ trans('Slectionner ...') }}</option>
                    @foreach(App\Models\Evaluation::TYPE_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('type', $evaluation->type) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('type'))
                    <div class="invalid-feedback">
                        {{ $errors->first('type') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('type_helper') }}</span>
            </div>


             <table class=" table table-bordered table-striped table-hover datatable datatable-Note">
                <thead>
                    <tr>
                        <th>
                            {{ trans('eleve') }}
                        </th>
                        <th>
                            {{ trans('valeur') }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($evaluation->evaluationNotes as $key => $note)
                        <tr data-entry-id="{{ $note->id }}" style="border:solid 1px black">
                            <td>
                                {{ $note->eleve->prenom ?? '' }} {{ $note->eleve->nom ?? '' }}
                            </td>
                            <td>
                                <label style="width:40px">{{ $note->valeur ?? '' }}</label>
                                <input  name="notes[{{$note->id}}]" id="notes[{{$note->id}}]" value="{{ $note->valeur ?? '0' }}">
                            </td>
                            <td>
                                {{ $note->eleve->prenom_ar ?? '' }} {{ $note->eleve->nom_ar ?? '' }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('Enregistrer') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/evaluations/index.blade.php
@extends('layouts.backend')
@section('content')
<div class="container">

    <a class="btn btn-success" href="{{ route("evaluations.create") }}">
        Nouvelle évaluation
    </a>
    <div class="row">
        @include('admin.sidebar')

        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Liste des évaluations
                </div>
                <div class="card-body">
                    <form method="get" class="inline">
                        <select name="classe_id" id="classe_id" >
                        <option value="">Tous</option>
                            @foreach($classes as $classe)
                                <option value="{{$classe->id}}" {{ ($classe_id == $classe->id)? 'selected' : '' }}>{{ $classe->niveau->libelle ?? '' }}</option>
                            @endforeach
                        </select>
                        <select name="type" id="type" >
                            <option value="">Tous</option>
                            <option value="D" {{ ($type == 'D')? 'selected' : '' }}>Devoir</option>
                            <option value="C1" {{ ($type == 'C1')? 'selected' : '' }}>Composition 1</option>
                            <option value="C2" {{ ($type == 'C2')? 'selected' : '' }}>Composition 2</option>
                            <option value="C3" {{ ($type == 'C3')? 'selected' : '' }}>Composition 3</option>
                        </select>
                        <button type="submit">Recherche</button>
                    </form>
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Evaluation">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        Classe
                                    </th>
                                    <th>
                                        Date
                                    </th>
                                    <th>
                                        Matière
                                    </th>
                                    <th>
                                        /Base
                                    </th>
                                    <th>
                                        Coef.
                                    </th>
                                    <th>
                                        Type
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($evaluations as $key => $evaluation)
                                    <tr data-entry-id="{{ $evaluation->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $evaluation->classe->niveau->libelle ?? ''  }} {{ $evaluation->classe->numero ?? ''  }}
                                        </td>
                                        <td>
                                            {{ $evaluation->date_evaluation ?? '' }}
                                        </td>
                                        <td>
                                            {{ $evaluation->matiere->libelle ?? '' }}
                                        </td>
                                        <td>
                                            {{ $evaluation->matiere->base ?? '' }}
                                        </td>
                                        <td>
                                            {{ $evaluation->matiere->coefficient ?? '' }}
                                        </td>
                                        <td>
                                            {{ App\Models\Evaluation::TYPE_SELECT[$evaluation->type] ?? '' }}
                                        </td>
                                        <td>
                                            <a class="btn btn-xs btn-primary" href="{{ route('evaluations.show', $evaluation->id) }}">
                                                {{ trans('Afficher') }}
                                            </a>
                                            <a class="btn btn-xs btn-info" href="{{ route('evaluations.edit', $evaluation->id) }}">
                                                {{ trans('Modifier') }}
                                            </a><form action="{{ route('evaluations.destroy', $evaluation->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('Supprimer') }}">
                                            </form>
                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('evaluation_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('evaluations.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Evaluation:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/evaluations/show.blade.php
@extends('layouts.backend')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Voir') }} {{ trans('cruds.evaluation.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('evaluations.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
                @foreach(App\Models\Evaluation::TYPE_SELECT as $key => $label)
                    <option value="{{ $key }}" {{ old('type', '') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    <a class="btn btn-primary" href="{{ route('evaluations.index') }}">
                        {{ $label }}
                    </a>
                @endforeach
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr data-entry-id="{{ $evaluation->id }}">
                        <td>

                        </td>
                        <td>
                            {{ $evaluation->classe->niveau->libelle ?? '' }}
                        </td>
                        <td>
                            {{ $evaluation->date_evaluation ?? '' }}
                        </td>
                        <td>
                            {{ $evaluation->matiere->libelle ?? '' }}
                        </td>
                        <td>
                            {{ App\Models\Evaluation::TYPE_SELECT[$evaluation->type] ?? '' }}
                        </td>

                    </tr>
                </tbody>
            </table>

            <table class=" table table-bordered table-striped table-hover datatable datatable-Note">
                <thead>
                    <tr>
                        <th>
                            {{ trans('Eleve') }}
                        </th>
                        <th>
                            {{ trans('Note') }} / {{ $evaluation->matiere->base ?? '' }}
                        </th>

                        <th>
                            {{ trans('الإسم') }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($evaluation->evaluationNotes as $key => $note)
                        <tr data-entry-id="{{ $note->id }}">
                            <td>
                                {{ $note->eleve->prenom ?? '' }} {{ $note->eleve->nom ?? '' }}
                            </td>
                            <td>
                                {{ $note->valeur ?? '' }}
                            </td>
                            <td>
                                {{ $note->eleve->prenom_ar ?? '' }} {{ $note->eleve->nom_ar ?? '' }}
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="form-group">
                <a class="btn btn-default" href="{{ route('evaluations.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection