routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin');
});

Auth::routes(['register' => true]);

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['namespace' => 'App\Http\Controllers\Admin', 'prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('users', 'UsersController');
    Route::resource('contrats', 'ContratsController');
    Route::resource('personnes', 'PersonnesController');
    Route::resource('pages', 'PagesController');
    Route::resource('activitylogs', 'ActivityLogsController')->only([
        'index', 'show', 'destroy'
    ]);
    Route::resource('admin/settings', 'SettingsController');
    Route::get('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
    Route::post('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
});

Route::group(['namespace' => 'App\Http\Controllers\Admin', 'prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'AdminController@index');
    Route::get('evaluations/create/{id}', 'EvaluationController@create');
    Route::resource('annee', 'AnneeController');
    Route::resource('cycles', 'CyclesController');
    Route::resource('niveau', 'NiveauController');
    Route::resource('classes', 'ClassesController');
    Route::resource('eleves', 'ElevesController');
    
    Route::resource('matieres', 'MatieresController');
    Route::resource('evaluations', 'EvaluationController');
    Route::resource('notes', 'NoteController');

    //ListeElevesParClasseController

    Route::resource('matieres', 'MatieresController');
});

//Editions
Route::group(['namespace' => 'App\Http\Controllers\Editions', 'prefix' => 'editions', 'middleware' => ['auth']], function () {

    //Liste des Eleves Par Classe
    Route::get('classe/eleves/{classe_id}', 'ListeElevesParClasseController@tousLesEleves')->name('listes.classe.eleves');
    // Exporter les eleves en fichier Excel
    Route::post("eleves/export", "EelveExcelController@export")->name('eleves.excel.export');
});

// Bulletins
Route::get('bulletins/eleves/{eleve}/{eval}', '\App\Http\Controllers\Admin\EleveController@bulletin')->name('bulletins.eleve.eval');
Route::get('bulletins/classe/{classe}/{eval}', '\App\Http\Controllers\Admin\ClassesController@bulletin')->name('bulletins.classe.eval');
Route::resource('bulletins', 'BulletinController');

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Note extends Model
{
    use SoftDeletes;

    public $table = 'notes';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'valeur',
        'eleve_id',
        'created_at',
        'updated_at',
        'deleted_at',
        'evaluation_id',
    ];

    public function eleve()
    {
        return $this->belongsTo(Eleve::class, 'eleve_id');
    }

    public function evaluation()
    {
        return $this->belongsTo(Evaluation::class, 'evaluation_id');
    }
}

app/Http/Controllers/Admin/NoteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Evaluation;
use App\Http\Controllers\Controller;

use App\Models\Eleve;
use App\Models\Note;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class NoteController extends Controller
{
    public function index()
    {
        //abort_if(Gate::denies('note_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $notes = Note::all();

        return view('admin.notes.index', compact('notes'));
    }

    public function create()
    {
        //abort_if(Gate::denies('note_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        //$eleves = Eleve::all()->pluck('nom', 'id')->prepend(trans('Slectionner ...'), '');
        $eleves = Eleve::orderBy('classe_id')->get();

        //$evaluations = Evaluation::all()->pluck('date_evaluation', 'id')->prepend(trans('Slectionner ...'), '');
        $evaluations = Evaluation::orderBy('classe_id')->get();
        return view('admin.notes.create', compact('eleves', 'evaluations'));
    }

    public function store(Request $request)
    {
        $note = Note::create($request->all());

        return redirect()->route('notes.index');
    }

    public function edit(Note $note)
    {
        //abort_if(Gate::denies('note_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $eleves = Eleve::all()->pluck('nom', 'id')->prepend(trans('Slectionner ...'), '');

        $evaluations = Evaluation::all()->pluck('date_evaluation', 'id')->prepend(trans('Slectionner ...'), '');

        $note->load('eleve', 'evaluation');

        return view('admin.notes.edit', compact('eleves', 'evaluations', 'note'));
    }

    public function update(Request $request, Note $note)
    {
        $note->update($request->all());

        return redirect()->route('notes.index');
    }

    public function show(Note $note)
    {
        //abort_if(Gate::denies('note_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $note->load('eleve', 'evaluation');

        return view('admin.notes.show', compact('note'));
    }

    public function destroy(Note $note)
    {
        //abort_if(Gate::denies('note_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $note->delete();

        return back();
    }

    public function massDestroy(Request $request)
    {
        Note::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/notes/create.blade.php
@extends('layouts.backend')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Ajouter') }} {{ trans('Note') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("notes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="eleve_id">{{ trans('eleve') }}</label>
                <select class="form-control select2 {{ $errors->has('eleve') ? 'is-invalid' : '' }}" name="eleve_id" id="eleve_id">
                <option value="" > Selectionnez ...</option>
                    @foreach($eleves as  $eleve)
                        @if($eleve->classe != null)
                            <option value="{{ $eleve->id }}" > {{ $eleve->classe->niveau->libelle}} : {{ $eleve->prenom }} {{ $eleve->nom }}</option>
                        @endif
                    @endforeach
                </select>
                @if($errors->has('eleve_id'))
                    <div class="invalid-feedback">
                        {{ $errors->first('eleve_id') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('eleve_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="evaluation_id">{{ trans('evaluation') }}</label>
                <select class="form-control select2 {{ $errors->has('evaluation') ? 'is-invalid' : '' }}" name="evaluation_id" id="evaluation_id">
                <option value="" > Selectionnez ...</option>
                    @foreach($evaluations as  $evaluation)
                        @if($evaluation->matiere != null)
                            <option value="{{ $evaluation->id }}" > {{ $evaluation->type }} : {{ $evaluation->classe->niveau->libelle}} : {{ $evaluation->matiere->libelle}}  </option>
                        @endif
                    @endforeach
                </select>
                @if($errors->has('evaluation_id'))
                    <div class="invalid-feedback">
                        {{ $errors->first('evaluation_id') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('evaluation_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="valeur">{{ trans('valeur') }}</label>
                <input class="form-control {{ $errors->has('valeur') ? 'is-invalid' : '' }}" type="number" name="valeur" id="valeur" value="{{ old('valeur') }}" step="0.01" max="20">
                @if($errors->has('valeur'))
                    <div class="invalid-feedback">
                        {{ $errors->first('valeur') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('valeur_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('Enregistrer') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/notes/edit.blade.php
@extends('layouts.backend')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Modifier') }} {{ trans('Note') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("notes.update", [$note->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="eleve_id">{{ trans('eleve') }}</label>
                <select class="form-control select2 {{ $errors->has('eleve') ? 'is-invalid' : '' }}" name="eleve_id" id="eleve_id">
                    @foreach($eleves as $id => $eleve)
                        <option value="{{ $id }}" {{ ($note->eleve ? $note->eleve->id : old('eleve_id')) == $id ? 'selected' : '' }}>{{ $eleve }}</option>
                    @endforeach
                </select>
                @if($errors->has('eleve_id'))
                    <div class="invalid-feedback">
                        {{ $errors->first('eleve_id') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('eleve_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="evaluation_id">{{ trans('evaluation') }}</label>
                <select class="form-control select2 {{ $errors->has('evaluation') ? 'is-invalid' : '' }}" name="evaluation_id" id="evaluation_id">
                    @foreach($evaluations as $id => $evaluation)
                        <option value="{{ $id }}" {{ ($note->evaluation ? $note->evaluation->id : old('evaluation_id')) == $id ? 'selected' : '' }}>{{ $evaluation }}</option>
                    @endforeach
                </select>
                @if($errors->has('evaluation_id'))
                    <div class="invalid-feedback">
                        {{ $errors->first('evaluation_id') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('evaluation_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="valeur">{{ trans('valeur') }}</label>
                <input class="form-control {{ $errors->has('valeur') ? 'is-invalid' : '' }}" type="number" name="valeur" id="valeur" value="{{ old('valeur', $note->valeur) }}" step="0.01" max="20">
                @if($errors->has('valeur'))
                    <div class="invalid-feedback">
                        {{ $errors->first('valeur') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('valeur_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('Enregistrer') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/notes/index.blade.php
@extends('layouts.backend')
@section('content')

            <a class="btn btn-success" href="{{ route("notes.create") }}">
                Ajouter une note
            </a>
    <div class="row">
        @include('admin.sidebar')

        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    {{ trans('Note') }} {{ trans('Liste') }}
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Note">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        #
                                    </th>
                                    <th>
                                        Nom d'élève
                                    </th>
                                    <th>
                                        Evaluation
                                    </th>
                                    <th>
                                        Note
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($notes as $key => $note)
                                    <tr data-entry-id="{{ $note->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $note->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $note->eleve->prenom_ar ?? '' }} {{ $note->eleve->nom_ar ?? '' }}
                                        </td>
                                        <td>
                                            @if($note->evaluation)
                                                {{ $note->evaluation::TYPE_SELECT[$note->evaluation->type] ?? '' }}
                                                {{ $note->evaluation->matiere->libelle ?? '' }}
                                                {{ $note->evaluation->date_evaluation ?? '' }}
                                            @endif
                                        </td>
                                        <td>
                                            {{ $note->valeur ?? '' }}
                                        </td>
                                        <td>
                                            @can('note_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('notes.show', $note->id) }}">
                                                    {{ trans('Afficher') }}
                                                </a>
                                            @endcan

                                            @can('note_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('notes.edit', $note->id) }}">
                                                    {{ trans('Modifier') }}
                                                </a>
                                            @endcan

                                            @can('note_delete')
                                                <form action="{{ route('notes.destroy', $note->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('Supprimer') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('note_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('notes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Note:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/notes/show.blade.php
@extends('layouts.backend')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Voir') }} {{ trans('cruds.note.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('notes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('id') }}
                        </th>
                        <td>
                            {{ $note->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('eleve') }}
                        </th>
                        <td>
                            {{ $note->eleve->nom ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('evaluation') }}
                        </th>
                        <td>
                            {{ $note->evaluation->date_evaluation ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('valeur') }}
                        </th>
                        <td>
                            {{ $note->valeur }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('notes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection